---
- name: Ansible playbook interacting with 
  hosts: localhost
  connection: local
  
  vars:
    apod_url: "http://www.omdbapi.com/?i=tt3896198&apikey=" # API to call
    mykey: "{{ lookup('file', '~/nasa.key') }}"  # our api key

  tasks:
  - name: Send HTTP GET to NASA api
    uri:
      method: GET     # send this method
      url: "{{ apod_url }}{{ mykey }}"
    register: nasaread
    
  - name: Display the contents of the variable 'nasaread'
    debug:
      var: nasaread
      
  - name: Display just the Actors
    debug:
      var: nasaread.json.get('Actors')
      
  - name: Display just the BoxOffice
    debug:
      var: nasaread.json.get('BoxOffice',"No HD URL for today!")

